/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.QueryPagamento;
import QueryesPesonalizadas.QueryesFornecedor;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.RollbackException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelos.Factory;
import modelos.Fornecedor;
import modelos.Pagamento;
import modelos.Produto;

/**
 *
 * @author pedro
 */
public class CadastrarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CadastrarFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
        MaskFormatter cpf;
        try {
            cpf = new MaskFormatter("###.###.###-##");
            jtfCpfCnpj.setValue(null);
            jtfCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(cpf));
            jRCpf.setSelected(true);
            jtfNomeFornecedor.grabFocus();
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

        ImageIcon iconEmp = new ImageIcon("src/images/growthcode.png");
        iconEmp.setImage(iconEmp.getImage().getScaledInstance(391, 260, 1));
        jlbImgImp.setIcon(iconEmp);
        jtableFornecedor.setRowHeight(28);
    }
    Fornecedor fornecedor = new Fornecedor();
    Factory fac = new Factory();
    EntityManager em = fac.retornaEntidadegerenciada();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        root = new javax.swing.JPanel();
        cadastrar = new javax.swing.JPanel();
        jtfNomeFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jRCpf = new javax.swing.JRadioButton();
        jRCnpj = new javax.swing.JRadioButton();
        jtfCpfCnpj = new javax.swing.JFormattedTextField();
        jtfContato = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jlbImgImp = new javax.swing.JLabel();
        jbtSalvar = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        pesquisar = new javax.swing.JPanel();
        jbtVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSrcolpaneInterno = new javax.swing.JScrollPane();
        jtableFornecedor = new javax.swing.JTable();
        jtfPesquisaPorNomeFornecedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        root.setLayout(new java.awt.CardLayout());

        jtfNomeFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfNomeFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeFornecedorKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Nome do fornecedor:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Contato:");

        jtfCidade.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyPressed(evt);
            }
        });

        jRCpf.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jRCpf.setText("CPF");
        jRCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCpfActionPerformed(evt);
            }
        });

        jRCnpj.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jRCnpj.setText("CNPJ");
        jRCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCnpjActionPerformed(evt);
            }
        });

        jtfCpfCnpj.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        try {
            jtfContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)  #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfContato.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Cidade:");

        jbtSalvar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        jbtPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastrarLayout = new javax.swing.GroupLayout(cadastrar);
        cadastrar.setLayout(cadastrarLayout);
        cadastrarLayout.setHorizontalGroup(
            cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarLayout.createSequentialGroup()
                        .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(cadastrarLayout.createSequentialGroup()
                            .addComponent(jbtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastrarLayout.createSequentialGroup()
                            .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cadastrarLayout.createSequentialGroup()
                                    .addComponent(jRCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRCnpj)))
                            .addGap(28, 28, 28)
                            .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarLayout.createSequentialGroup()
                    .addContainerGap(482, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(241, 241, 241)))
        );
        cadastrarLayout.setVerticalGroup(
            cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarLayout.createSequentialGroup()
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRCpf)
                            .addComponent(jRCnpj)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarLayout.createSequentialGroup()
                        .addComponent(jbtSalvar)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarLayout.createSequentialGroup()
                        .addComponent(jbtPesquisar)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarLayout.createSequentialGroup()
                        .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadastrarLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel6)
                    .addContainerGap(468, Short.MAX_VALUE)))
        );

        root.add(cadastrar, "cadastrar");

        jbtVoltar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jSrcolpaneInterno.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jSrcolpaneInterno.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jSrcolpaneInterno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jtableFornecedor.setAutoCreateRowSorter(true);
        jtableFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jtableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fornecedor", "Nome do Fornecedor", "Cidade", "Cpf/cnpj", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableFornecedor.setDoubleBuffered(true);
        jtableFornecedor.setDragEnabled(true);
        jtableFornecedor.setFillsViewportHeight(true);
        jtableFornecedor.setFocusCycleRoot(true);
        jtableFornecedor.setFocusTraversalPolicyProvider(true);
        jtableFornecedor.setGridColor(new java.awt.Color(0, 51, 255));
        jtableFornecedor.setInheritsPopupMenu(true);
        jtableFornecedor.setSurrendersFocusOnKeystroke(true);
        jtableFornecedor.getTableHeader().setReorderingAllowed(false);
        jtableFornecedor.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jtableFornecedorHierarchyChanged(evt);
            }
        });
        jtableFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtableFornecedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtableFornecedorFocusLost(evt);
            }
        });
        jtableFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtableFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtableFornecedorKeyReleased(evt);
            }
        });
        jSrcolpaneInterno.setViewportView(jtableFornecedor);
        if (jtableFornecedor.getColumnModel().getColumnCount() > 0) {
            jtableFornecedor.getColumnModel().getColumn(0).setResizable(false);
            jtableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtableFornecedor.getColumnModel().getColumn(1).setResizable(false);
            jtableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(230);
            jtableFornecedor.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtableFornecedor.getColumnModel().getColumn(4).setPreferredWidth(90);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSrcolpaneInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jtfPesquisaPorNomeFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaPorNomeFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfPesquisaPorNomeFornecedorFocusGained(evt);
            }
        });
        jtfPesquisaPorNomeFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaPorNomeFornecedorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Pesquisa por nome do fornecedor:");

        jbtExcluir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pesquisarLayout = new javax.swing.GroupLayout(pesquisar);
        pesquisar.setLayout(pesquisarLayout);
        pesquisarLayout.setHorizontalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfPesquisaPorNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pesquisarLayout.createSequentialGroup()
                            .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );
        pesquisarLayout.setVerticalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesquisaPorNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtVoltar)
                    .addComponent(jbtExcluir))
                .addGap(80, 80, 80))
        );

        root.add(pesquisar, "editar");

        getContentPane().add(root, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_jtfNomeFornecedorKeyPressed

    private void jtfCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCidadeKeyPressed

    private void jRCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCpfActionPerformed
        MaskFormatter cpf;
        try {
            cpf = new MaskFormatter("###.###.###-##");
            jtfCpfCnpj.setValue(null);
            jtfCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(cpf));
            jRCnpj.setSelected(false);
            jtfCpfCnpj.grabFocus();
        } catch (ParseException ex) {
            Logger.getLogger(CadastrarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRCpfActionPerformed

    private void jRCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCnpjActionPerformed
        MaskFormatter cnpj;
        try {
            cnpj = new MaskFormatter("##.###.###/####-##");
            jtfCpfCnpj.setValue(null);
            jtfCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(cnpj));
            jRCpf.setSelected(false);
            jtfCpfCnpj.grabFocus();

        } catch (ParseException ex) {
            Logger.getLogger(CadastrarFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRCnpjActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        cadastrar();
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "editar");

    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "cadastrar");
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtableFornecedorHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jtableFornecedorHierarchyChanged

    }//GEN-LAST:event_jtableFornecedorHierarchyChanged

    private void jtableFornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtableFornecedorFocusGained

    }//GEN-LAST:event_jtableFornecedorFocusGained

    private void jtableFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtableFornecedorFocusLost

    }//GEN-LAST:event_jtableFornecedorFocusLost

    private void jtableFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableFornecedorKeyPressed

    }//GEN-LAST:event_jtableFornecedorKeyPressed

    private void jtableFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtableFornecedorKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int linha = jtableFornecedor.getSelectedRow();
            int coluna = jtableFornecedor.getSelectedColumn();
            editarFornecedor(linha, coluna);

        }
    }//GEN-LAST:event_jtableFornecedorKeyReleased

    private void jtfPesquisaPorNomeFornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeFornecedorFocusGained
        if (jtableFornecedor.isEditing()) {
           jtableFornecedor.getCellEditor().stopCellEditing();
        }
    }//GEN-LAST:event_jtfPesquisaPorNomeFornecedorFocusGained

    private void jtfPesquisaPorNomeFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeFornecedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<Fornecedor> lista = new ArrayList<>();
            lista = pesquisaPorNome(jtfPesquisaPorNomeFornecedor.getText());

            DefaultTableModel dtm = (DefaultTableModel) jtableFornecedor.getModel();
            for (int i = jtableFornecedor.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCidade(),
                    lista.get(i).getCpfCnpj(),
                    lista.get(i).getContato()
                   

                });

            }

        }
    }//GEN-LAST:event_jtfPesquisaPorNomeFornecedorKeyPressed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        try {

            int linha = jtableFornecedor.getSelectedRow();

            int id = Integer.parseInt(jtableFornecedor.getValueAt(linha, 0).toString());

           Fornecedor f =  em.find(Fornecedor.class, id);
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente Excluir o Fornecedor?", "Janela de confirmação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                em.getTransaction().begin();
                em.remove(f);
                em.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Fornecedor Excluido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                DefaultTableModel dtm = (DefaultTableModel) jtableFornecedor.getModel();

                dtm.removeRow(linha);
                jtfPesquisaPorNomeFornecedor.grabFocus();
                jtfPesquisaPorNomeFornecedor.setText("");
            }
            if (resposta == JOptionPane.NO_OPTION) {
                jtfPesquisaPorNomeFornecedor.grabFocus();
                jtfPesquisaPorNomeFornecedor.selectAll();
            }

        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nenhum Fornecedor selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            jtfPesquisaPorNomeFornecedor.grabFocus();
            jtfPesquisaPorNomeFornecedor.selectAll();
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFornecedor().setVisible(true);
            }
        });
    }

    public void cadastrar() {
        int x = 0;

        fornecedor.setNome(jtfNomeFornecedor.getText());
        fornecedor.setCidade(jtfCidade.getText());
        fornecedor.setCpfCnpj(jtfCpfCnpj.getText());
        fornecedor.setContato(jtfContato.getText());

        if (jtfNomeFornecedor.getText().length() <= 0 || jtfCidade.getText().length() <= 0
                || jtfCpfCnpj.getText().length() <= 0 || jtfContato.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Tente corrigir os valores dos campos de acordo com o que se pede!", "Alerta!", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                em.getTransaction().begin();
                em.persist(fornecedor);
                em.getTransaction().commit();
                limparCampos();
                JOptionPane.showMessageDialog(null, "Fornecedor Criado com Sucesso!", "alerta", JOptionPane.INFORMATION_MESSAGE);
                em.clear();

                jtfNomeFornecedor.grabFocus();

                fornecedor = new Fornecedor();

            } catch (RollbackException e) {

                JOptionPane.showMessageDialog(null, "Não é possivel cadastrar Fornecedores  descrição Iguais ", "alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public void editarFornecedor(int linha, int coluna) {

        String conteudo = jtableFornecedor.getValueAt(linha, coluna) + "";
        Fornecedor f = new Fornecedor();
        f.setId(Integer.parseInt(jtableFornecedor.getValueAt(linha,0).toString()));
        f.setNome(jtableFornecedor.getValueAt(linha, 1).toString());
        f.setCidade(jtableFornecedor.getValueAt(linha, 2).toString());
        f.setCpfCnpj(jtableFornecedor.getValueAt(linha, 3).toString());
        f.setContato(jtableFornecedor.getValueAt(linha, 4).toString());

        try {

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este Fornecedor?", "Janela de Confimação", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.NO_OPTION) {
                // preencherTabelaPorNome(nomePesquisado);
                jtfPesquisaPorNomeFornecedor.grabFocus();
                jtfPesquisaPorNomeFornecedor.selectAll();
            }
            if (resposta == JOptionPane.YES_OPTION) {
                em.getTransaction().begin();
                em.merge(f);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Fornecedor Editado com Sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                prencherPorId(f);
                jtfPesquisaPorNomeFornecedor.grabFocus();
                jtfPesquisaPorNomeFornecedor.selectAll();
            }

        } catch (RollbackException e) {
            JOptionPane.showMessageDialog(null, "Houve um erro na tentativa de edição!");
            jtfPesquisaPorNomeFornecedor.grabFocus();
        }
    }

    public void limparCampos() {
        jtfCidade.setText("");
        jtfContato.setText("");
        jtfCpfCnpj.setText("");
        jtfNomeFornecedor.setText("");
    }

    public void prencherPorId(Fornecedor f) {
        f = em.find(Fornecedor.class, f.getId());
        DefaultTableModel dtm = (DefaultTableModel) jtableFornecedor.getModel();
        dtm.setNumRows(0);
        dtm.addRow(new Object[]{
            f.getId(),
            f.getNome(),
            f.getCidade(),
            f.getCpfCnpj(),
            f.getContato()
        });
    }
    public List<Fornecedor> pesquisaPorNome(String nome) {
        QueryesFornecedor qf = new QueryesFornecedor();
       return qf.retornaForncedorPorNome(nome);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRCnpj;
    private javax.swing.JRadioButton jRCpf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jSrcolpaneInterno;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JLabel jlbImgImp;
    private javax.swing.JTable jtableFornecedor;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JFormattedTextField jtfContato;
    private javax.swing.JFormattedTextField jtfCpfCnpj;
    private javax.swing.JTextField jtfNomeFornecedor;
    private javax.swing.JTextField jtfPesquisaPorNomeFornecedor;
    private javax.swing.JPanel pesquisar;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
