/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.QueryesUsuario;
import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.RollbackException;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelos.Acesso;
import modelos.Factory;
import modelos.Usuario;
import org.eclipse.persistence.exceptions.DatabaseException;
import org.eclipse.persistence.queries.InsertObjectQuery;

/**
 *
 * @author Max Cell
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    EntityManager em;
    Factory factory = new Factory();
    private static CadastrarUsuario cu;
    List<JCheckBox> nova = new ArrayList<>();
    Usuario usuario = new Usuario();
    Acesso acesso = new Acesso();

    public static CadastrarUsuario getInstancia() {
        if (cu == null) {
            cu = new CadastrarUsuario();
        }
        return cu;
    }

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        em = factory.retornaEntidadegerenciada();
        jtfNomeUsuario.grabFocus();
        DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer();
        tableCellRenderer.setBackground(Color.getHSBColor(50, 1, 30));
        tableCellRenderer.setForeground(Color.WHITE);
        jSrcolpaneInterno.getViewport().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRoot = new javax.swing.JPanel();
        PanelSalvar = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jtfNomeUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfLoginUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcheckUsuario = new javax.swing.JCheckBox();
        jcheckVendedor = new javax.swing.JCheckBox();
        jbtSalvar = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        jcheckAdmin = new javax.swing.JCheckBox();
        PanelPesquisar = new javax.swing.JPanel();
        jbtVoltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPesquisaCodigoUsuario = new javax.swing.JTextField();
        jtfPesquisaPorNomeUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSrcolpaneInterno = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelRoot.setPreferredSize(new java.awt.Dimension(920, 600));
        PanelRoot.setLayout(new java.awt.CardLayout());

        PanelSalvar.setPreferredSize(new java.awt.Dimension(920, 590));

        jtfNomeUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeUsuarioKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Nome do usuario: ");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Login do usuario:");

        jtfLoginUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfLoginUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfLoginUsuarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Inserir uma senha: ");

        jtfSenha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Permissões : ");

        jcheckUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jcheckUsuario.setText(" 3- Usuario ");
        jcheckUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckUsuarioActionPerformed(evt);
            }
        });

        jcheckVendedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jcheckVendedor.setText(" 2- Vendedor");
        jcheckVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckVendedorActionPerformed(evt);
            }
        });

        jbtSalvar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtPesquisar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        jcheckAdmin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jcheckAdmin.setText(" 1- Admin");
        jcheckAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSalvarLayout = new javax.swing.GroupLayout(PanelSalvar);
        PanelSalvar.setLayout(PanelSalvarLayout);
        PanelSalvarLayout.setHorizontalGroup(
            PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(240, 240, 240)
                .addComponent(jLabel2))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jtfLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jcheckAdmin))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jcheckVendedor))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jcheckUsuario))
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jbtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(509, 509, 509)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelSalvarLayout.setVerticalGroup(
            PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalvarLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGroup(PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSalvarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSalvarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)))
                .addGap(35, 35, 35)
                .addComponent(jcheckAdmin)
                .addGap(7, 7, 7)
                .addComponent(jcheckVendedor)
                .addGap(7, 7, 7)
                .addComponent(jcheckUsuario)
                .addGap(97, 97, 97)
                .addGroup(PanelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalvar)
                    .addComponent(jbtPesquisar)))
        );

        PanelRoot.add(PanelSalvar, "SalvarUsuario");

        jbtVoltar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtVoltar.setText("Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Codigo do Produto: ");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Pesquisa por descrição:");

        jtfPesquisaCodigoUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaCodigoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfPesquisaCodigoUsuarioFocusGained(evt);
            }
        });

        jtfPesquisaPorNomeUsuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaPorNomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfPesquisaPorNomeUsuarioFocusGained(evt);
            }
        });
        jtfPesquisaPorNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaPorNomeUsuarioKeyPressed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jSrcolpaneInterno.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N

        jTableUsuarios.setAutoCreateRowSorter(true);
        jTableUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do usuario", "Nome do usuario", "Login do usuario", "Senha do usuario", "Nivel de acesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setCellSelectionEnabled(true);
        jTableUsuarios.setDoubleBuffered(true);
        jTableUsuarios.setFillsViewportHeight(true);
        jTableUsuarios.setFocusCycleRoot(true);
        jTableUsuarios.setFocusTraversalPolicyProvider(true);
        jTableUsuarios.setGridColor(new java.awt.Color(0, 51, 255));
        jTableUsuarios.setSurrendersFocusOnKeystroke(true);
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableUsuarios.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTableUsuariosHierarchyChanged(evt);
            }
        });
        jTableUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableUsuariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableUsuariosFocusLost(evt);
            }
        });
        jTableUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableUsuariosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableUsuariosKeyReleased(evt);
            }
        });
        jSrcolpaneInterno.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(180);
            jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableUsuarios.getColumnModel().getColumn(3).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableUsuarios.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout PanelPesquisarLayout = new javax.swing.GroupLayout(PanelPesquisar);
        PanelPesquisar.setLayout(PanelPesquisarLayout);
        PanelPesquisarLayout.setHorizontalGroup(
            PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPesquisarLayout.createSequentialGroup()
                .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPesquisarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPesquisarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPesquisarLayout.createSequentialGroup()
                                .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfPesquisaCodigoUsuario))
                                .addGap(36, 36, 36)
                                .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPesquisarLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfPesquisaPorNomeUsuario))))))
                .addGap(75, 75, 75))
        );
        PanelPesquisarLayout.setVerticalGroup(
            PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPesquisarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisaCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisaPorNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jbtVoltar)
                .addGap(134, 134, 134))
        );

        PanelRoot.add(PanelPesquisar, "PesquisarUsuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelRoot.getAccessibleContext().setAccessibleName("root");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PesquisarUsuario");
        jtfPesquisaPorNomeUsuario.grabFocus();
    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        cadastrar();
        jtfNomeUsuario.grabFocus();
        limparCampos();
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jcheckAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckAdminActionPerformed
        selecionarCaixas(true, jcheckAdmin);


    }//GEN-LAST:event_jcheckAdminActionPerformed

    private void jcheckVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckVendedorActionPerformed
        List<JCheckBox> lista = new ArrayList<>();
        lista.add(jcheckAdmin);
        // lista.add(jcheckTodosPriviegios);
        lista.add(jcheckUsuario);

        List<JCheckBox> nova = new ArrayList<>();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).isSelected()) {

                lista.get(i).setSelected(false);
            }
        }
    }//GEN-LAST:event_jcheckVendedorActionPerformed

    private void jcheckUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckUsuarioActionPerformed
        List<JCheckBox> lista = new ArrayList<>();
        lista.add(jcheckAdmin);
        //lista.add(jcheckTodosPriviegios);
        lista.add(jcheckVendedor);

        List<JCheckBox> nova = new ArrayList<>();
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).isSelected()) {

                lista.get(i).setSelected(false);
            }
        }


    }//GEN-LAST:event_jcheckUsuarioActionPerformed

    private void jtfNomeUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfLoginUsuario.grabFocus();
        }
    }//GEN-LAST:event_jtfNomeUsuarioKeyPressed

    private void jtfLoginUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLoginUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtfSenha.grabFocus();
        }
    }//GEN-LAST:event_jtfLoginUsuarioKeyPressed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "SalvarUsuario");
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jtfPesquisaPorNomeUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<Usuario> lista = new ArrayList<>();
            lista = pesquisaPorNome(jtfPesquisaPorNomeUsuario.getText());

            DefaultTableModel dtm = (DefaultTableModel) jTableUsuarios.getModel();
            for (int i = jTableUsuarios.getRowCount() - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getUser(),
                    lista.get(i).getSenha(),
                    lista.get(i).getAcesso().getId()
                });

            }

        }
    }//GEN-LAST:event_jtfPesquisaPorNomeUsuarioKeyPressed

    private void jTableUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUsuariosKeyPressed

    }//GEN-LAST:event_jTableUsuariosKeyPressed

    private void jTableUsuariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableUsuariosFocusLost
        
    }//GEN-LAST:event_jTableUsuariosFocusLost

    private void jTableUsuariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableUsuariosFocusGained


    }//GEN-LAST:event_jTableUsuariosFocusGained

    private void jTableUsuariosHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTableUsuariosHierarchyChanged

    }//GEN-LAST:event_jTableUsuariosHierarchyChanged

    private void jTableUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUsuariosKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int linha = jTableUsuarios.getSelectedRow();
            int coluna = jTableUsuarios.getSelectedColumn();
            editarUsuario(linha, coluna);
            
        }

    }//GEN-LAST:event_jTableUsuariosKeyReleased

    private void jtfPesquisaPorNomeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeUsuarioFocusGained
        if(jTableUsuarios.isEditing()){
             jTableUsuarios.getCellEditor().stopCellEditing();
         }
    }//GEN-LAST:event_jtfPesquisaPorNomeUsuarioFocusGained

    private void jtfPesquisaCodigoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPesquisaCodigoUsuarioFocusGained
         if(jTableUsuarios.isEditing()){
             jTableUsuarios.getCellEditor().stopCellEditing();
         }
    }//GEN-LAST:event_jtfPesquisaCodigoUsuarioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    public void selecionarCaixas(boolean s, JCheckBox c) {
        if (c.isSelected()) {
            jcheckAdmin.setSelected(s);
            jcheckUsuario.setSelected(s);
            jcheckVendedor.setSelected(s);
            // jcheckTodosPriviegios.setSelected(s);

        } else {
            jcheckAdmin.setSelected(!s);
            // jcheckTodosPriviegios.setSelected(!s);
            jcheckUsuario.setSelected(!s);
            jcheckVendedor.setSelected(!s);
        }
    }

    public void cadastrar() {

        usuario.setNome(jtfNomeUsuario.getText());
        usuario.setUser(jtfLoginUsuario.getText());
        usuario.setSenha(jtfSenha.getText());

        if (usuario.getNome().equals("") || usuario.getSenha().equals("") || usuario.getUser().equals("")) {
            JOptionPane.showMessageDialog(null, "Existem alguns campos que não forma preenchidos", "Alerta!", JOptionPane.WARNING_MESSAGE);

        } else {
            List<JCheckBox> lista = new ArrayList<>();

            // lista.add(jcheckTodosPriviegios);
            lista.add(jcheckAdmin);
            lista.add(jcheckVendedor);
            lista.add(jcheckUsuario);

            for (int i = 0; i < lista.size(); i++) {
                if (lista.get(i).isSelected()) {
                    nova.add(lista.get(i));

                }
            }

            if (nova.isEmpty()) {
                JOptionPane.showMessageDialog(null, "nenhum tipo de acesso ao sistema foi marcado para o usuario", "Alerta!", JOptionPane.WARNING_MESSAGE);

            } else {
                try {

                    String valor = String.valueOf(nova.get(0).getText().charAt(1));
                    JOptionPane.showMessageDialog(null, valor);
                    nova = nova = new ArrayList<JCheckBox>();
                    acesso = em.find(Acesso.class, Integer.parseInt(valor));
                    usuario.setAcesso(acesso);
                    JOptionPane.showMessageDialog(null, usuario.getAcesso().getTipo());

                    em.getTransaction().begin();
                    em.persist(usuario);
                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Usuario criado com sucesso!", "alerta", JOptionPane.INFORMATION_MESSAGE);
                    em.clear();
                    usuario = new Usuario();

                } catch (RollbackException e) {

                    JOptionPane.showMessageDialog(null, "Não é possivel cadastrar usuarios com login ou nomes iguais", "alerta", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }

    public void limparCampos() {
        jtfLoginUsuario.setText("");
        jtfNomeUsuario.setText("");
        jtfSenha.setText("");
        jcheckAdmin.setSelected(false);
        jcheckUsuario.setSelected(false);
        jcheckVendedor.setSelected(false);

    }

    public List<Usuario> pesquisaPorNome(String nome) {
        QueryesUsuario qu = new QueryesUsuario();
        return qu.retornaUsuariosPorNome(nome);
    }

    public void editarUsuario(int linha, int coluna) {

        String conteudo = jTableUsuarios.getValueAt(linha, coluna) + "";
        Usuario  usuario = new Usuario();
            usuario.setId(Integer.parseInt(jTableUsuarios.getValueAt(linha,0).toString()));
            usuario.setNome(jTableUsuarios.getValueAt(linha,1).toString());
            usuario.setUser(jTableUsuarios.getValueAt(linha,2).toString());
            usuario.setSenha(jTableUsuarios.getValueAt(linha,3).toString());
            Acesso a = new Acesso();
            a.setId(Integer.parseInt(jTableUsuarios.getValueAt(linha,4).toString()));
            usuario.setAcesso(a);
        try{
            
          int resposta = JOptionPane.showConfirmDialog(null,"Deseja realmente alterar este usuario?","Janela de Confimação", JOptionPane.YES_NO_OPTION);
          if(resposta== JOptionPane.YES_NO_OPTION){
              
          }if(resposta== JOptionPane.YES_OPTION){
              em.getTransaction().begin();
         em.merge(usuario);
         em.getTransaction().commit();
         JOptionPane.showMessageDialog(null,"Usuario Editado com Sucesso!","Alerta",JOptionPane.INFORMATION_MESSAGE);
         jtfPesquisaPorNomeUsuario.grabFocus();
          }
          
        }catch(RollbackException e){
             JOptionPane.showMessageDialog(null,"Houve um erro na tentativa de edição!");
             jtfPesquisaPorNomeUsuario.grabFocus();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPesquisar;
    private javax.swing.JPanel PanelRoot;
    private javax.swing.JPanel PanelSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane jSrcolpaneInterno;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JCheckBox jcheckAdmin;
    private javax.swing.JCheckBox jcheckUsuario;
    private javax.swing.JCheckBox jcheckVendedor;
    private javax.swing.JTextField jtfLoginUsuario;
    private javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JTextField jtfPesquisaCodigoUsuario;
    private javax.swing.JTextField jtfPesquisaPorNomeUsuario;
    private javax.swing.JTextField jtfSenha;
    // End of variables declaration//GEN-END:variables
}
