/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.QueryPedido;
import QueryesPesonalizadas.QueryesCliente;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modellosUteis.PedidoCompletoo;
import modelos.Cliente;
import modelos.Conexao;
import modelos.Factory;
import modelos.Pedido;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.joda.time.LocalDate;

/**
 *
 * @author pedro
 */
public class PedidoRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form PedidoRelatorio
     */
    Factory fac = new Factory();
    EntityManager em = fac.retornaEntidadegerenciada();
    private static PedidoRelatorio pedidoRelatorio;

    public static PedidoRelatorio getInstancia() {
        if (pedidoRelatorio == null) {
            pedidoRelatorio = new PedidoRelatorio();
        }
        return pedidoRelatorio;
    }

    public PedidoRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        jtablePedido.setRowHeight(28);
        ImageIcon iconEmp = new ImageIcon("src/images/growthcode.png");
        iconEmp.setImage(iconEmp.getImage().getScaledInstance(336, 209, 1));
        jlbImgImp.setIcon(iconEmp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        jcbDataPedido = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoCliente = new javax.swing.JTextField();
        jtfNomeCliente = new javax.swing.JTextField();
        jbtPesquisarCliente = new javax.swing.JButton();
        jbtBuscarPorPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlbImgImp = new javax.swing.JLabel();
        geraçao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSrcolpaneInterno1 = new javax.swing.JScrollPane();
        jtablePedido = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbtFechar = new javax.swing.JButton();
        jlbResults = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jSrcolpaneInterno2 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jtfPesquisaPorNomeCliente = new javax.swing.JTextField();
        jbtFechar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        root.setLayout(new java.awt.CardLayout());

        jcbDataPedido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Data do pedido: ");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Codigo:");

        jtfCodigoCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoClienteActionPerformed(evt);
            }
        });

        jtfNomeCliente.setEditable(false);
        jtfNomeCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeClienteActionPerformed(evt);
            }
        });

        jbtPesquisarCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtPesquisarCliente.setText("...");
        jbtPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarClienteActionPerformed(evt);
            }
        });

        jbtBuscarPorPedido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtBuscarPorPedido.setText("Buscar por Pedido");
        jbtBuscarPorPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarPorPedidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Cliente: ");

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtBuscarPorPedido)
                    .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jcbDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(inicioLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4))
                        .addGroup(inicioLayout.createSequentialGroup()
                            .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(inicioLayout.createSequentialGroup()
                                    .addComponent(jtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtPesquisarCliente))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jcbDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesquisarCliente)
                    .addComponent(jtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jbtBuscarPorPedido)
                .addGap(48, 48, 48))
        );

        root.add(inicio, "inicio");

        jSrcolpaneInterno1.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jtablePedido.setAutoCreateRowSorter(true);
        jtablePedido.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jtablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Nome do  cliente", "Cpf / cnpj", "Data do pedido", "Total do Pedido $", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtablePedido.setDoubleBuffered(true);
        jtablePedido.setDragEnabled(true);
        jtablePedido.setFillsViewportHeight(true);
        jtablePedido.setFocusCycleRoot(true);
        jtablePedido.setFocusTraversalPolicyProvider(true);
        jtablePedido.setGridColor(new java.awt.Color(0, 51, 255));
        jtablePedido.setInheritsPopupMenu(true);
        jtablePedido.setSurrendersFocusOnKeystroke(true);
        jtablePedido.getTableHeader().setReorderingAllowed(false);
        jtablePedido.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jtablePedidoHierarchyChanged(evt);
            }
        });
        jtablePedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtablePedidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtablePedidoFocusLost(evt);
            }
        });
        jtablePedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablePedidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtablePedidoMousePressed(evt);
            }
        });
        jtablePedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtablePedidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablePedidoKeyReleased(evt);
            }
        });
        jSrcolpaneInterno1.setViewportView(jtablePedido);
        if (jtablePedido.getColumnModel().getColumnCount() > 0) {
            jtablePedido.getColumnModel().getColumn(0).setPreferredWidth(15);
            jtablePedido.getColumnModel().getColumn(1).setPreferredWidth(170);
            jtablePedido.getColumnModel().getColumn(3).setPreferredWidth(30);
            jtablePedido.getColumnModel().getColumn(4).setPreferredWidth(40);
            jtablePedido.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Selecionar um pedido para geração do relatorio:");

        jbtFechar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });

        jlbResults.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Resultados: ");

        javax.swing.GroupLayout geraçaoLayout = new javax.swing.GroupLayout(geraçao);
        geraçao.setLayout(geraçaoLayout);
        geraçaoLayout.setHorizontalGroup(
            geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geraçaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(geraçaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbResults, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jbtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(geraçaoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(98, Short.MAX_VALUE))))
            .addGroup(geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(geraçaoLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        geraçaoLayout.setVerticalGroup(
            geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geraçaoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addGroup(geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtFechar)
                    .addGroup(geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbResults, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(38, 38, 38))
            .addGroup(geraçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(geraçaoLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        root.add(geraçao, "geracao");

        jSrcolpaneInterno2.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jTableCliente.setAutoCreateRowSorter(true);
        jTableCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Nome do  Cliente", "Cpf/cnpj", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setDoubleBuffered(true);
        jTableCliente.setDragEnabled(true);
        jTableCliente.setFillsViewportHeight(true);
        jTableCliente.setFocusCycleRoot(true);
        jTableCliente.setFocusTraversalPolicyProvider(true);
        jTableCliente.setGridColor(new java.awt.Color(0, 51, 255));
        jTableCliente.setInheritsPopupMenu(true);
        jTableCliente.setSurrendersFocusOnKeystroke(true);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jTableCliente.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTableClienteHierarchyChanged(evt);
            }
        });
        jTableCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableClienteFocusLost(evt);
            }
        });
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableClienteMousePressed(evt);
            }
        });
        jTableCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableClienteKeyReleased(evt);
            }
        });
        jSrcolpaneInterno2.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(180);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSrcolpaneInterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jtfPesquisaPorNomeCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaPorNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaPorNomeClienteActionPerformed(evt);
            }
        });
        jtfPesquisaPorNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaPorNomeClienteKeyPressed(evt);
            }
        });

        jbtFechar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtFechar1.setText("Fechar");
        jbtFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFechar1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Pesquisa por nome do cliente:");

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clienteLayout.createSequentialGroup()
                .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtFechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clienteLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPesquisaPorNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
            .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clienteLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(39, 39, 39)))
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesquisaPorNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jbtFechar1)
                .addGap(62, 62, 62))
            .addGroup(clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(clienteLayout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        root.add(cliente, "cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeClienteActionPerformed

    private void jbtBuscarPorPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarPorPedidoActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        DateFormat f = DateFormat.getDateInstance();
        Date d1 = null;

        String data = sdf.format(jcbDataPedido.getDate());

        try {
            d1 = sdf.parse(data);
        } catch (ParseException ex) {
            Logger.getLogger(PedidoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }

        List<PedidoCompletoo> lista = new ArrayList<>();
        lista = buscarPedido(Integer.parseInt(jtfCodigoCliente.getText()), data);

        DefaultTableModel dtm = (DefaultTableModel) jtablePedido.getModel();
        dtm.setNumRows(0);
        if (lista.size() == 0) {
            JOptionPane.showMessageDialog(null, "Numero de pedidos é : " + lista.size());
        } else {
            for (int i = 0; i < lista.size(); i++) {

                dtm.addRow(new Object[]{
                    lista.get(i).getId_pedido(),
                    lista.get(i).getNome_cliente(),
                    lista.get(i).getCpf_cliente(),
                    formatador.format(lista.get(i).getData()),
                    lista.get(i).getVALOR_TOTAL_PEDIDO(),
                    lista.get(i).getNome()

                });

                CardLayout card = (CardLayout) root.getLayout();
                card.show(root, "geracao");
                jlbResults.setText(lista.size() + "");
            }

    }//GEN-LAST:event_jbtBuscarPorPedidoActionPerformed
    }
    private void jtablePedidoHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jtablePedidoHierarchyChanged

    }//GEN-LAST:event_jtablePedidoHierarchyChanged

    private void jtablePedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtablePedidoFocusGained

    }//GEN-LAST:event_jtablePedidoFocusGained

    private void jtablePedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtablePedidoFocusLost

    }//GEN-LAST:event_jtablePedidoFocusLost

    private void jtablePedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablePedidoMouseClicked
        int linha = jtablePedido.getSelectedRow();
        Long idPedido = Long.parseLong(jtablePedido.getValueAt(linha,0).toString());
        HashMap params = new HashMap<>();
            params.put("idPedido",idPedido );

            JasperPrint jp = null;
        try {
            jp = JasperFillManager.fillReport("src/relatorio/r/projeto.jasper", params, Conexao.conecta());
        } catch (SQLException ex) {
            Logger.getLogger(PedidoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PedidoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(PedidoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JasperViewer jv = new JasperViewer(jp, false);

            jv.setVisible(true);
    }//GEN-LAST:event_jtablePedidoMouseClicked

    private void jtablePedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablePedidoMousePressed


    }//GEN-LAST:event_jtablePedidoMousePressed

    private void jtablePedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablePedidoKeyPressed

    }//GEN-LAST:event_jtablePedidoKeyPressed

    private void jtablePedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablePedidoKeyReleased

    }//GEN-LAST:event_jtablePedidoKeyReleased

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "inicio");
    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jtfCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoClienteActionPerformed
        try {

            int idCliente = Integer.parseInt(jtfCodigoCliente.getText());
            jtfNomeCliente.setText(em.find(Cliente.class, idCliente).getNome_cliente());

        } catch (NullPointerException e) {
            jtfCodigoCliente.selectAll();
            JOptionPane.showMessageDialog(null, "Cliente não cadastrado!");
        } catch (NumberFormatException e) {
            jtfNomeCliente.setText("");
            JOptionPane.showMessageDialog(null, "Campo codigo não pode ser vazio!");
        }
    }//GEN-LAST:event_jtfCodigoClienteActionPerformed

    private void jTableClienteHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTableClienteHierarchyChanged

    }//GEN-LAST:event_jTableClienteHierarchyChanged

    private void jTableClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableClienteFocusGained

    }//GEN-LAST:event_jTableClienteFocusGained

    private void jTableClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableClienteFocusLost

    }//GEN-LAST:event_jTableClienteFocusLost

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked

        jtfCodigoCliente.setText(jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 0).toString());
        jtfNomeCliente.setText(jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1).toString());
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "inicio");
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jTableClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMousePressed
        /*int linha = jTableFornecedor.getSelectedRow();
        int resposta = JOptionPane.showConfirmDialog(null, "Forncedor selelionado: " + jTableFornecedor.getValueAt(linha, 1).toString() + "", "Escolha de Fornecedor", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {

            FornecedorUtil.setForncedorUtil(em.find(Fornecedor.class,jTableFornecedor.getValueAt(linha,0) ));
            this.setVisible(false);

        } else if (resposta == JOptionPane.NO_OPTION) {

        }*/
    }//GEN-LAST:event_jTableClienteMousePressed

    private void jTableClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClienteKeyPressed

    }//GEN-LAST:event_jTableClienteKeyPressed

    private void jTableClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClienteKeyReleased

    }//GEN-LAST:event_jTableClienteKeyReleased

    private void jtfPesquisaPorNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaPorNomeClienteActionPerformed

    private void jtfPesquisaPorNomeClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<Cliente> lista = new ArrayList<>();
            lista = pesquisaPorNome(jtfPesquisaPorNomeCliente.getText());

            DefaultTableModel dtm = (DefaultTableModel) jTableCliente.getModel();
            dtm.setNumRows(0);
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(new Object[]{
                    lista.get(i).getId_cliente(),
                    lista.get(i).getNome_cliente(),
                    lista.get(i).getCpf_cliente(), // lista.get(i).getTelefone(),
                });

            }

        }
    }//GEN-LAST:event_jtfPesquisaPorNomeClienteKeyPressed

    private void jbtFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFechar1ActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "inicio");
    }//GEN-LAST:event_jbtFechar1ActionPerformed

    private void jbtPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarClienteActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "cliente");
    }//GEN-LAST:event_jbtPesquisarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoRelatorio().setVisible(true);
            }
        });
    }

    public List<PedidoCompletoo> buscarPedido(int idCliente, String data) {
        QueryPedido qp = new QueryPedido();
        return qp.retornaPedido(idCliente, data);

    }

    public List<Cliente> pesquisaPorNome(String nome) {
        QueryesCliente qc = new QueryesCliente();
        return qc.retornaClientePorNome(nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cliente;
    private javax.swing.JPanel geraçao;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jSrcolpaneInterno1;
    private javax.swing.JScrollPane jSrcolpaneInterno2;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JButton jbtBuscarPorPedido;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtFechar1;
    private javax.swing.JButton jbtPesquisarCliente;
    private de.wannawork.jcalendar.JCalendarComboBox jcbDataPedido;
    private javax.swing.JLabel jlbImgImp;
    private javax.swing.JLabel jlbResults;
    private javax.swing.JTable jtablePedido;
    private javax.swing.JTextField jtfCodigoCliente;
    private javax.swing.JTextField jtfNomeCliente;
    private javax.swing.JTextField jtfPesquisaPorNomeCliente;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
