/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.QueryesFornecedor;
import QueryesPesonalizadas.QueryesUsuario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modellosUteis.FornecedorUtil;
import modelos.Factory;
import modelos.Fornecedor;
import modelos.Usuario;

/**
 *
 * @author pedro
 */
public class PesquisaRapidaFornecedor extends javax.swing.JFrame {
    Factory fac = new Factory();
    EntityManager em = fac.retornaEntidadegerenciada();
    private static PesquisaRapidaFornecedor PRF;
     public static PesquisaRapidaFornecedor getInstancia() {
        if (PRF == null) {
            PRF = new PesquisaRapidaFornecedor();
        }
        return PRF;
    }
     
     public static void setarCampoIdForncedor(){
         
     }
    /**
     * Creates new form PesquisaRapidaFornecedor
     */
    public PesquisaRapidaFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
        jtfPesquisaPorNomeForncedor.grabFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfPesquisaPorNomeForncedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSrcolpaneInterno1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jbtFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtfPesquisaPorNomeForncedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaPorNomeForncedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaPorNomeForncedorActionPerformed(evt);
            }
        });
        jtfPesquisaPorNomeForncedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaPorNomeForncedorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa por nome:");

        jSrcolpaneInterno1.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jTableFornecedor.setAutoCreateRowSorter(true);
        jTableFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Nome do  Forncedor", "Cidade", "Cpf / cnpj", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedor.setDoubleBuffered(true);
        jTableFornecedor.setDragEnabled(true);
        jTableFornecedor.setFillsViewportHeight(true);
        jTableFornecedor.setFocusCycleRoot(true);
        jTableFornecedor.setFocusTraversalPolicyProvider(true);
        jTableFornecedor.setGridColor(new java.awt.Color(0, 51, 255));
        jTableFornecedor.setInheritsPopupMenu(true);
        jTableFornecedor.setSurrendersFocusOnKeystroke(true);
        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTableFornecedorHierarchyChanged(evt);
            }
        });
        jTableFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableFornecedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableFornecedorFocusLost(evt);
            }
        });
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableFornecedorMousePressed(evt);
            }
        });
        jTableFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableFornecedorKeyReleased(evt);
            }
        });
        jSrcolpaneInterno1.setViewportView(jTableFornecedor);
        if (jTableFornecedor.getColumnModel().getColumnCount() > 0) {
            jTableFornecedor.getColumnModel().getColumn(0).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableFornecedor.getColumnModel().getColumn(1).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableFornecedor.getColumnModel().getColumn(2).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(3).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jbtFechar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jtfPesquisaPorNomeForncedor, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jbtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisaPorNomeForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtFechar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFornecedorHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTableFornecedorHierarchyChanged

    }//GEN-LAST:event_jTableFornecedorHierarchyChanged

    private void jTableFornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableFornecedorFocusGained

    }//GEN-LAST:event_jTableFornecedorFocusGained

    private void jTableFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableFornecedorFocusLost

    }//GEN-LAST:event_jTableFornecedorFocusLost

    private void jTableFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFornecedorKeyPressed

    }//GEN-LAST:event_jTableFornecedorKeyPressed

    private void jTableFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFornecedorKeyReleased


    }//GEN-LAST:event_jTableFornecedorKeyReleased

    private void jtfPesquisaPorNomeForncedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeForncedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaPorNomeForncedorActionPerformed

    private void jTableFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMousePressed
        /*int linha = jTableFornecedor.getSelectedRow();
        int resposta = JOptionPane.showConfirmDialog(null, "Forncedor selelionado: " + jTableFornecedor.getValueAt(linha, 1).toString() + "", "Escolha de Fornecedor", JOptionPane.YES_NO_OPTION);
         
        if (resposta == JOptionPane.YES_OPTION) {
            
                  FornecedorUtil.setForncedorUtil(em.find(Fornecedor.class,jTableFornecedor.getValueAt(linha,0) ));
                 this.setVisible(false);
                  
        } else if (resposta == JOptionPane.NO_OPTION) {
                
        }*/
    }//GEN-LAST:event_jTableFornecedorMousePressed

    private void jtfPesquisaPorNomeForncedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeForncedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<Fornecedor> lista = new ArrayList<>();
            lista = pesquisaPorNome(jtfPesquisaPorNomeForncedor.getText());

            DefaultTableModel dtm = (DefaultTableModel)jTableFornecedor.getModel();
                dtm.setNumRows(0);
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCidade(),
                    lista.get(i).getCpfCnpj(),
                    lista.get(i).getContato()
                });

            }

        }
    }//GEN-LAST:event_jtfPesquisaPorNomeForncedorKeyPressed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaRapidaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaRapidaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaRapidaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaRapidaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaRapidaFornecedor().setVisible(true);
            }
        });
    }

    public List<Fornecedor> pesquisaPorNome(String nome) {
        QueryesFornecedor qf = new QueryesFornecedor();
        return qf.retornaForncedorPorNome(nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jSrcolpaneInterno;
    private javax.swing.JScrollPane jSrcolpaneInterno1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JTextField jtfPesquisaPorNomeForncedor;
    // End of variables declaration//GEN-END:variables
}
