/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import QueryesPesonalizadas.QueryesFornecedor;
import QueryesPesonalizadas.QueryesUsuario;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modellosUteis.FornecedorUtil;
import modelos.Conexao;
import modelos.Factory;
import modelos.Fornecedor;
import modelos.Usuario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pedro
 */
public class ProdutoRelatorio extends javax.swing.JFrame {

    Factory fac = new Factory();
    EntityManager em = fac.retornaEntidadegerenciada();
    private static ProdutoRelatorio PRF;

    public static ProdutoRelatorio getInstancia() {
        if (PRF == null) {
            PRF = new ProdutoRelatorio();
        }
        return PRF;
    }

    public static void setarCampoIdForncedor() {

    }

    /**
     * Creates new form PesquisaRapidaFornecedor
     */
    public ProdutoRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        jtfPesquisaPorNomeForncedor.grabFocus();
        ImageIcon iconEmp = new ImageIcon("src/images/growthcode.png");
        iconEmp.setImage(iconEmp.getImage().getScaledInstance(291, 217, 1));
        jlbImgImp.setIcon(iconEmp);
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "relatorio");
        jTableFornecedor.setRowHeight(28);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        pesquisar = new javax.swing.JPanel();
        jbtFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSrcolpaneInterno1 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        jtfPesquisaPorNomeForncedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        relatorio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoFornecedor = new javax.swing.JTextField();
        jbtPesquisarForncedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpInfo = new javax.swing.JTextPane();
        jbtGerar = new javax.swing.JButton();
        jlbImgImp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        root.setLayout(new java.awt.CardLayout());

        jbtFechar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });

        jSrcolpaneInterno1.setBackground(new java.awt.Color(102, 102, 255));
        jSrcolpaneInterno1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jTableFornecedor.setAutoCreateRowSorter(true);
        jTableFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 15)); // NOI18N
        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Nome do  Fornecedor", "Cidade", "Cpf / cnpj", "Contato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedor.setDoubleBuffered(true);
        jTableFornecedor.setDragEnabled(true);
        jTableFornecedor.setFillsViewportHeight(true);
        jTableFornecedor.setFocusCycleRoot(true);
        jTableFornecedor.setFocusTraversalPolicyProvider(true);
        jTableFornecedor.setGridColor(new java.awt.Color(0, 51, 255));
        jTableFornecedor.setInheritsPopupMenu(true);
        jTableFornecedor.setSurrendersFocusOnKeystroke(true);
        jTableFornecedor.getTableHeader().setReorderingAllowed(false);
        jTableFornecedor.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTableFornecedorHierarchyChanged(evt);
            }
        });
        jTableFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableFornecedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableFornecedorFocusLost(evt);
            }
        });
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableFornecedorMousePressed(evt);
            }
        });
        jTableFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableFornecedorKeyReleased(evt);
            }
        });
        jSrcolpaneInterno1.setViewportView(jTableFornecedor);
        if (jTableFornecedor.getColumnModel().getColumnCount() > 0) {
            jTableFornecedor.getColumnModel().getColumn(0).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableFornecedor.getColumnModel().getColumn(1).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableFornecedor.getColumnModel().getColumn(2).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(3).setResizable(false);
            jTableFornecedor.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSrcolpaneInterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jtfPesquisaPorNomeForncedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jtfPesquisaPorNomeForncedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaPorNomeForncedorActionPerformed(evt);
            }
        });
        jtfPesquisaPorNomeForncedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisaPorNomeForncedorKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa por nome:");

        javax.swing.GroupLayout pesquisarLayout = new javax.swing.GroupLayout(pesquisar);
        pesquisar.setLayout(pesquisarLayout);
        pesquisarLayout.setHorizontalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(pesquisarLayout.createSequentialGroup()
                        .addGroup(pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfPesquisaPorNomeForncedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(jbtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pesquisarLayout.setVerticalGroup(
            pesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesquisaPorNomeForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jbtFechar)
                .addGap(31, 31, 31))
        );

        root.add(pesquisar, "pesquisar");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Codigo do Fornecedor:");

        jtfCodigoFornecedor.setBackground(new java.awt.Color(153, 255, 255));
        jtfCodigoFornecedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtfCodigoFornecedor.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jtfCodigoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoFornecedorActionPerformed(evt);
            }
        });
        jtfCodigoFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoFornecedorKeyPressed(evt);
            }
        });

        jbtPesquisarForncedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jbtPesquisarForncedor.setText("Pesquisar");
        jbtPesquisarForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtPesquisarForncedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtPesquisarForncedorMousePressed(evt);
            }
        });
        jbtPesquisarForncedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarForncedorActionPerformed(evt);
            }
        });
        jbtPesquisarForncedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtPesquisarForncedorKeyPressed(evt);
            }
        });

        jtpInfo.setEditable(false);
        jtpInfo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jtpInfo.setCaretColor(new java.awt.Color(204, 204, 204));
        jtpInfo.setEnabled(false);
        jScrollPane2.setViewportView(jtpInfo);

        jbtGerar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jbtGerar.setText("Gerar Relatorio");
        jbtGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout relatorioLayout = new javax.swing.GroupLayout(relatorio);
        relatorio.setLayout(relatorioLayout);
        relatorioLayout.setHorizontalGroup(
            relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatorioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relatorioLayout.createSequentialGroup()
                        .addGroup(relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(relatorioLayout.createSequentialGroup()
                                .addComponent(jtfCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtPesquisarForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(relatorioLayout.createSequentialGroup()
                        .addComponent(jbtGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(relatorioLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        relatorioLayout.setVerticalGroup(
            relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatorioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesquisarForncedor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jlbImgImp, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtGerar)
                .addGap(37, 37, 37))
        );

        root.add(relatorio, "relatorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFornecedorHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTableFornecedorHierarchyChanged

    }//GEN-LAST:event_jTableFornecedorHierarchyChanged

    private void jTableFornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableFornecedorFocusGained

    }//GEN-LAST:event_jTableFornecedorFocusGained

    private void jTableFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableFornecedorFocusLost

    }//GEN-LAST:event_jTableFornecedorFocusLost

    private void jTableFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFornecedorKeyPressed

    }//GEN-LAST:event_jTableFornecedorKeyPressed

    private void jTableFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFornecedorKeyReleased


    }//GEN-LAST:event_jTableFornecedorKeyReleased

    private void jtfPesquisaPorNomeForncedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeForncedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaPorNomeForncedorActionPerformed

    private void jTableFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMousePressed
        /*int linha = jTableFornecedor.getSelectedRow();
        int resposta = JOptionPane.showConfirmDialog(null, "Forncedor selelionado: " + jTableFornecedor.getValueAt(linha, 1).toString() + "", "Escolha de Fornecedor", JOptionPane.YES_NO_OPTION);
         
        if (resposta == JOptionPane.YES_OPTION) {
            
                  FornecedorUtil.setForncedorUtil(em.find(Fornecedor.class,jTableFornecedor.getValueAt(linha,0) ));
                 this.setVisible(false);
                  
        } else if (resposta == JOptionPane.NO_OPTION) {
                
        }*/
    }//GEN-LAST:event_jTableFornecedorMousePressed

    private void jtfPesquisaPorNomeForncedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaPorNomeForncedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<Fornecedor> lista = new ArrayList<>();
            lista = pesquisaPorNome(jtfPesquisaPorNomeForncedor.getText());

            DefaultTableModel dtm = (DefaultTableModel) jTableFornecedor.getModel();
            dtm.setNumRows(0);
            for (int i = 0; i < lista.size(); i++) {
                dtm.addRow(new Object[]{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCidade(),
                    lista.get(i).getCpfCnpj(),
                    lista.get(i).getContato()
                });

            }

        }
    }//GEN-LAST:event_jtfPesquisaPorNomeForncedorKeyPressed

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "relatorio");
    }//GEN-LAST:event_jbtFecharActionPerformed

    private void jtfCodigoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoFornecedorActionPerformed

    }//GEN-LAST:event_jtfCodigoFornecedorActionPerformed

    private void jtfCodigoFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoFornecedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {

                Fornecedor f = em.find(Fornecedor.class, Integer.parseInt(jtfCodigoFornecedor.getText()));
                jtpInfo.setText(f.getNome());
            } catch (NullPointerException e) {
                jtpInfo.setText("");
                
                 JOptionPane.showMessageDialog(null,"Fornecedor não encontado");
            }
        }
    }//GEN-LAST:event_jtfCodigoFornecedorKeyPressed

    private void jbtPesquisarForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtPesquisarForncedorMouseClicked

    }//GEN-LAST:event_jbtPesquisarForncedorMouseClicked

    private void jbtPesquisarForncedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtPesquisarForncedorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPesquisarForncedorMousePressed

    private void jbtPesquisarForncedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarForncedorActionPerformed
        CardLayout card = (CardLayout) root.getLayout();
        card.show(root, "pesquisar");
    }//GEN-LAST:event_jbtPesquisarForncedorActionPerformed

    private void jbtPesquisarForncedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtPesquisarForncedorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CardLayout card = (CardLayout) root.getLayout();
            card.show(root, "pesquisar");

        }
    }//GEN-LAST:event_jbtPesquisarForncedorKeyPressed

    private void jbtGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGerarActionPerformed
        try {
            
            HashMap params = new HashMap<>();
            params.put("fornecedor", Integer.parseInt(jtfCodigoFornecedor.getText()));
            JasperPrint jp = JasperFillManager.fillReport("src/relatorio/r/pedro.jasper", params, Conexao.conecta());
            JasperViewer jv = new JasperViewer(jp, false);

            jv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProdutoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(ProdutoRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"nenhum parametro informado" );
        }
    }//GEN-LAST:event_jbtGerarActionPerformed

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked
         
        
        jtfCodigoFornecedor.setText(jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(),0).toString());
        jtpInfo.setText(jTableFornecedor.getValueAt(jTableFornecedor.getSelectedRow(),1).toString());
         CardLayout card = (CardLayout) root.getLayout();
            card.show(root, "relatorio");
    }//GEN-LAST:event_jTableFornecedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoRelatorio().setVisible(true);
            }
        });
    }

    public List<Fornecedor> pesquisaPorNome(String nome) {
        QueryesFornecedor qf = new QueryesFornecedor();
        return qf.retornaForncedorPorNome(nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jSrcolpaneInterno1;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JButton jbtFechar;
    private javax.swing.JButton jbtGerar;
    private javax.swing.JButton jbtPesquisarForncedor;
    private javax.swing.JLabel jlbImgImp;
    private javax.swing.JTextField jtfCodigoFornecedor;
    private javax.swing.JTextField jtfPesquisaPorNomeForncedor;
    private javax.swing.JTextPane jtpInfo;
    private javax.swing.JPanel pesquisar;
    private javax.swing.JPanel relatorio;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
